import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import chalk from 'chalk';

export async function buildExtensionCommand() {
    const titanJsonPath = path.join(process.cwd(), 'titan.json');
    if (!fs.existsSync(titanJsonPath)) {
        console.log(chalk.red("✖ No titan.json found in current directory."));
        return;
    }

    const titanJson = JSON.parse(fs.readFileSync(titanJsonPath, 'utf8'));
    const type = titanJson.type;

    if (type === 'js') {
        console.log(chalk.yellow("! JS-only extensions do not require a build step."));
        return;
    }

    console.log(chalk.cyan(`\n→ Building ${type.toUpperCase()} extension '${titanJson.name}'...\n`));

    if (type === 'wasm') {
        await buildWasmExtension(titanJson);
    } else if (type === 'native') {
        await buildNativeExtension(titanJson);
    }
}

async function buildWasmExtension(titanJson) {
    const nativeDir = path.join(process.cwd(), 'native');
    if (!fs.existsSync(nativeDir)) {
        console.log(chalk.red("✖ native/ directory not found."));
        return;
    }

    console.log(chalk.gray("  Compiling Rust to WebAssembly..."));
    try {
        // We assume wasm-pack or similar is used, or just bare cargo with wasm32 target
        // The spec mentions: native/pkg/my_ext.wasm, which is wasm-pack's default
        execSync('wasm-pack build --target web', { cwd: nativeDir, stdio: 'inherit' });
    } catch (err) {
        console.log(chalk.red("✖ Wasm compilation failed. Make sure 'wasm-pack' is installed."));
        return;
    }

    console.log(chalk.gray("  Generating bindings..."));
    const libRsPath = path.join(nativeDir, 'src/lib.rs');
    const libRs = fs.readFileSync(libRsPath, 'utf8');
    
    const exports = [];
    const exportRegex = /#\[titan::export\]\s+pub\s+fn\s+(\w+)\s*\(([^)]*)\)\s*(?:->\s*([^\{]+))?/g;
    let match;
    while ((match = exportRegex.exec(libRs)) !== null) {
        const name = match[1];
        const paramsRaw = match[2];
        const params = paramsRaw.split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p);
        exports.push({ name, params });
    }

    const bindingsJs = `// Auto-generated by titan build ext
import * as wasm from './my_ext_bg.wasm';
export const { ${exports.map(e => e.name).join(', ')} } = wasm;
`;
    
    const pkgDir = path.join(nativeDir, 'pkg');
    fs.writeFileSync(path.join(pkgDir, 'bindings.js'), bindingsJs);

    // Update index.js
    const indexJs = `import { registerExtension } from './utils/registerExtension.js';
import * as native from './native/pkg/bindings.js';

const myExt = {
    ${exports.map(e => `${e.name}: (${e.params.join(', ')}) => native.${e.name}(${e.params.join(', ')})`).join(',\n    ')}
};

registerExtension("${titanJson.name.split('/').pop()}", myExt);
`;
    fs.writeFileSync(path.join(process.cwd(), 'index.js'), indexJs);

    // Update titan.json
    titanJson.wasm = "native/pkg/my_ext_bg.wasm";
    titanJson.bindings = "native/pkg/bindings.js";
    fs.writeFileSync(path.join(process.cwd(), 'titan.json'), JSON.stringify(titanJson, null, 2));

    console.log(chalk.green("✔ Wasm build complete."));
}

async function buildNativeExtension(titanJson) {
    const nativeDir = path.join(process.cwd(), 'native');
    if (!fs.existsSync(nativeDir)) {
        console.log(chalk.red("✖ native/ directory not found."));
        return;
    }

    console.log(chalk.gray("  Compiling Rust native library..."));
    try {
        execSync('cargo build --release', { cwd: nativeDir, stdio: 'inherit' });
    } catch (err) {
        console.log(chalk.red("✖ Native compilation failed."));
        return;
    }

    const libName = titanJson.name.split('/').pop().replace(/-/g, '_');
    const isWindows = process.platform === 'win32';
    const isMac = process.platform === 'darwin';
    
    let binName = `lib${libName}.so`;
    if (isWindows) binName = `${libName}.dll`;
    if (isMac) binName = `lib${libName}.dylib`;

    const buildDir = path.join(nativeDir, 'build');
    if (!fs.existsSync(buildDir)) fs.mkdirSync(buildDir);

    const targetDir = path.join(nativeDir, 'target/release');
    const srcPath = path.join(targetDir, binName);
    const destPath = path.join(buildDir, binName);

    if (fs.existsSync(srcPath)) {
        fs.copyFileSync(srcPath, destPath);
    }

    // Parse exports for index.js
    const libRsPath = path.join(nativeDir, 'src/lib.rs');
    const libRs = fs.readFileSync(libRsPath, 'utf8');
    const exports = [];
    const exportRegex = /#\[titan::native_export\]\s+pub\s+extern\s+"C"\s+fn\s+(\w+)\s*\(([^)]*)\)/g;
    let match;
    while ((match = exportRegex.exec(libRs)) !== null) {
        const name = match[1];
        const paramsRaw = match[2];
        const params = paramsRaw.split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p);
        exports.push({ name, params });
    }

    // Update index.js
    const indexJs = `import { registerExtension } from './utils/registerExtension.js';

// native bindings are injected by Gravity's NativeHost IPC bridge
const myExt = {
    ${exports.map(e => `${e.name}: (${e.params.join(', ')}) => t.__native.call("${titanJson.name}", "${e.name}", [${e.params.join(', ')}])`).join(',\n    ')}
};

registerExtension("${titanJson.name.split('/').pop()}", myExt);
`;
    fs.writeFileSync(path.join(process.cwd(), 'index.js'), indexJs);

    // Update titan.json
    titanJson.native = {
        linux: `native/build/lib${libName}.so`,
        windows: `native/build/${libName}.dll`,
        macos: `native/build/lib${libName}.dylib`
    };
    fs.writeFileSync(path.join(process.cwd(), 'titan.json'), JSON.stringify(titanJson, null, 2));

    console.log(chalk.green("✔ Native build complete."));
}
