import fs from 'fs';
import path from 'path';
import { execSync, spawn } from 'child_process';
import chalk from 'chalk';

export async function buildExtensionCommand() {
    const titanJsonPath = path.join(process.cwd(), 'titan.json');
    if (!fs.existsSync(titanJsonPath)) {
        console.log(chalk.red("✖ No titan.json found in current directory."));
        return;
    }

    const titanJson = JSON.parse(fs.readFileSync(titanJsonPath, 'utf8'));
    const type = titanJson.type;

    if (type === 'js') {
        console.log(chalk.yellow("! JS-only extensions do not require a build step."));
        return;
    }

    console.log(chalk.cyan(`\n→ Building ${type.toUpperCase()} extension '${titanJson.name}'...\n`));

    if (type === 'wasm') {
        await buildWasmExtension(titanJson);
    } else if (type === 'native') {
        if (fs.existsSync(path.join(process.cwd(), 'main.go'))) {
            await buildGoExtension(titanJson);
        } else {
            await buildNativeExtension(titanJson);
        }
    }
}

async function buildWasmExtension(titanJson) {
    const nativeDir = path.join(process.cwd(), 'native');
    if (!fs.existsSync(nativeDir)) {
        console.log(chalk.red("✖ native/ directory not found."));
        return;
    }

    console.log(chalk.gray("  Compiling Rust to WebAssembly..."));
    try {
        // We assume wasm-pack or similar is used, or just bare cargo with wasm32 target
        // The spec mentions: native/pkg/my_ext.wasm, which is wasm-pack's default
        console.log(chalk.gray("  Running wasm-pack..."));
        execSync('wasm-pack build --target web --no-typescript', { cwd: nativeDir, stdio: 'ignore' });
    } catch (err) {
        console.log(chalk.yellow("! wasm-pack failed, attempting raw cargo build..."));
        try {
            execSync('cargo build --target wasm32-unknown-unknown --release', { cwd: nativeDir, stdio: 'ignore' });
            const pkgDir = path.join(nativeDir, 'pkg');
            if (!fs.existsSync(pkgDir)) fs.mkdirSync(pkgDir);

            const targetWasm = path.join(nativeDir, `target/wasm32-unknown-unknown/release/${crateName}.wasm`);
            const destWasm = path.join(pkgDir, `${crateName}_bg.wasm`);
            fs.copyFileSync(targetWasm, destWasm);
            console.log(chalk.green("✔ Raw Wasm compilation successful."));
        } catch (cargoErr) {
            console.log(chalk.red("✖ Wasm compilation failed. Make sure Rust and wasm32-unknown-unknown target are installed."));
            return;
        }
    }

    console.log(chalk.gray("  Generating bindings..."));
    const libRsPath = path.join(nativeDir, 'src/lib.rs');
    const libRs = fs.readFileSync(libRsPath, 'utf8');

    const exports = [];
    const exportRegex = /#\[titan::export\]\s+pub\s+fn\s+(\w+)\s*\(([^)]*)\)\s*(?:->\s*([^\{]+))?/g;
    let match;
    while ((match = exportRegex.exec(libRs)) !== null) {
        const name = match[1];
        const paramsRaw = match[2];
        const params = paramsRaw.split(',').map(p => p.trim().split(':')[0].trim()).filter(p => p);
        exports.push({ name, params });
    }

    const bindingsJs = `// Auto-generated by titan build ext
import * as wasm from './my_ext_bg.wasm';
export const { ${exports.map(e => e.name).join(', ')} } = wasm;
`;

    const pkgDir = path.join(nativeDir, 'pkg');
    fs.writeFileSync(path.join(pkgDir, 'bindings.js'), bindingsJs);

    // Update index.js
    const indexJs = `import { registerExtension } from './utils/registerExtension.js';
import * as native from './native/pkg/bindings.js';

const myExt = {
    ${exports.map(e => `${e.name}: (${e.params.join(', ')}) => native.${e.name}(${e.params.join(', ')})`).join(',\n    ')}
};

registerExtension("${titanJson.name.split('/').pop()}", myExt);
`;
    fs.writeFileSync(path.join(process.cwd(), 'index.js'), indexJs);

    // Update titan.json
    titanJson.wasm = "native/pkg/my_ext_bg.wasm";
    titanJson.bindings = "native/pkg/bindings.js";
    fs.writeFileSync(path.join(process.cwd(), 'titan.json'), JSON.stringify(titanJson, null, 2));

    console.log(chalk.green("✔ Wasm build complete."));
}

async function buildNativeExtension(titanJson) {
    const nativeDir = path.join(process.cwd(), 'native');

    // ---------------------------------------------------
    // Validate native directory
    // ---------------------------------------------------
    if (!fs.existsSync(nativeDir)) {
        console.log(
            chalk.red("✖ native/ directory not found.")
        );
        return;
    }

    // ---------------------------------------------------
    // Resolve target binary path from titan.json
    // ---------------------------------------------------
    const isWindows = process.platform === 'win32';
    const isMac = process.platform === 'darwin';

    let configuredPath;

    if (isWindows) {
        configuredPath = titanJson.native?.windows;
    } else if (isMac) {
        configuredPath = titanJson.native?.macos;
    } else {
        configuredPath = titanJson.native?.linux;
    }

    if (!configuredPath) {
        console.log(
            chalk.red(
                "✖ Missing native binary path in titan.json"
            )
        );
        return;
    }

    const binName = path.basename(configuredPath);

    // ---------------------------------------------------
    // Build destination directory
    // ---------------------------------------------------
    const buildDir = path.dirname(
        path.join(process.cwd(), configuredPath)
    );

    if (!fs.existsSync(buildDir)) {
        fs.mkdirSync(buildDir, {
            recursive: true
        });
    }

    // ---------------------------------------------------
    // Start cargo build
    // ---------------------------------------------------
    console.log(
        chalk.cyan(`\n⏣ Forging Rust native extension...\n`)
    );

    try {
        await new Promise((resolve, reject) => {
            const build = spawn(
                'cargo',
                ['build', '--release'],
                {
                    cwd: nativeDir,
                    stdio: 'inherit'
                }
            );

            build.on('close', (code) => {
                if (code === 0) {
                    resolve();
                } else {
                    reject(
                        new Error(
                            `cargo exited with code ${code}`
                        )
                    );
                }
            });

            build.on('error', reject);
        });
    } catch (err) {
        console.log(
            chalk.red(
                `✖ Native compilation failed: ${err.message}`
            )
        );
        return;
    }

    // ---------------------------------------------------
    // Locate built binary
    // ---------------------------------------------------
    const targetDir = path.join(
        nativeDir,
        'target',
        'release'
    );

    const srcPath = path.join(
        targetDir,
        binName
    );

    const destPath = path.join(
        buildDir,
        binName
    );

    if (!fs.existsSync(srcPath)) {
        console.log(
            chalk.red(
                `✖ Compiled binary not found: ${srcPath}`
            )
        );

        console.log(
            chalk.yellow(
                `! Make sure Cargo.toml [lib] name matches the titan.json binary filename`
            )
        );

        return;
    }

    // ---------------------------------------------------
    // Copy binary
    // ---------------------------------------------------
    fs.copyFileSync(srcPath, destPath);

    console.log(
        chalk.green(
            `✔ Native binary copied → ${configuredPath}`
        )
    );

    // ---------------------------------------------------
    // Parse native exports
    // ---------------------------------------------------
    const libRsPath = path.join(
        nativeDir,
        'src',
        'lib.rs'
    );

    if (!fs.existsSync(libRsPath)) {
        console.log(
            chalk.red(
                "✖ native/src/lib.rs not found."
            )
        );
        return;
    }

    const libRs = fs.readFileSync(
        libRsPath,
        'utf8'
    );

    const exports = [];

    const exportRegex =
        /#\[titan::native_export\]\s+pub\s+extern\s+"C"\s+fn\s+(\w+)\s*\(([^)]*)\)/g;

    let match;

    while ((match = exportRegex.exec(libRs)) !== null) {
        const name = match[1];

        const paramsRaw = match[2];

        const params = paramsRaw
            .split(',')
            .map(p =>
                p.trim()
                 .split(':')[0]
                 .trim()
            )
            .filter(Boolean);

        exports.push({
            name,
            params
        });
    }

    // ---------------------------------------------------
    // Complete
    // ---------------------------------------------------
    console.log(
        chalk.green(
            `\n✔ Native extension build complete.\n`
        )
    );
}

async function buildGoExtension(titanJson) {
    const isWindows = process.platform === 'win32';

    // Retrieve output binary names from titan.json if available
    const winBin = titanJson.native?.windows || 'go-extension.dll';
    const linuxBin = titanJson.native?.linux || 'go-extension.so';

    const binaryName = isWindows ? winBin : linuxBin;

    console.log(chalk.gray(`  Compiling Go native library to ${binaryName}...`));

    try {
        const cmd = `go build -buildmode=c-shared -o "${binaryName}" main.go`;
        console.log(chalk.gray(`  Running: ${cmd}`));
        console.log(chalk.cyan("→ Starting Go compilation...\n"));

        await new Promise((resolve, reject) => {
            const build = spawn(
                'go',
                [
                    'build',
                    '-buildmode=c-shared',
                    '-o',
                    binaryName,
                    'main.go'
                ],
                {
                    cwd: process.cwd(),
                    stdio: 'inherit',
                }
            );

            build.on('close', (code) => {
                if (code === 0) {
                    resolve();
                } else {
                    reject(new Error(`go build exited with code ${code}`));
                }
            });

            build.on('error', reject);
        });
        console.log(chalk.green("✔ Go native build complete."));
    } catch (err) {
        console.log(chalk.red(`✖ Go compilation failed: ${err.message}`));
    }
}
